site:
  title: ngscopeclient Operator Manual
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
antora:
  extensions:
  - '@antora/pdf-extension'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
