site:
  title: ngscopeclient Operator Manual
  url: https://hansemro.github.io/scopehal-docs/
  start_page: ngscopeclient::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
antora:
  extensions:
  - '@antora/pdf-extension'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
